export const eventData = [
  {
    title: '2025 (Test)',
    customUrl: 'https://eigood.github.io/wicked-houston-data/iwwc-custom-20250601.json',
    infoUrl: 'https://eigood.github.io/wicked-houston-data/iwwc-info-20250601.json',
    startDate: '2025-06-01',
    endDate: '2025-07-05',
    primaryStat: null,
  },
  {
    title: 'Dominant Builder',
    description: 'Builder / Purifier',
    customUrl: 'https://eigood.github.io/wicked-houston-data/iwwc-custom-20250706.json',
    infoUrl: 'https://eigood.github.io/wicked-houston-data/iwwc-info-20250706.json',
    startDate: '2025-07-06',
    endDate: '2025-07-19',
    primaryStat: 'ratio@builder/purifier',
  },
  {
    title: 'Drone Hacker',
    description: 'Maverick',
    customUrl: 'https://eigood.github.io/wicked-houston-data/iwwc-custom-20250727.json',
    infoUrl: 'https://eigood.github.io/wicked-houston-data/iwwc-info-20250727.json',
    startDate: '2025-07-27',
    endDate: '2025-08-09',
    primaryStat: 'maverick',
  },
  {
    title: 'Link Protective Aura',
    description: 'Illuminator / Links Created',
    customUrl: 'https://eigood.github.io/wicked-houston-data/iwwc-custom-20250817.json',
    infoUrl: 'https://eigood.github.io/wicked-houston-data/iwwc-info-20250817.json',
    startDate: '2025-08-17',
    endDate: '2025-08-30',
    primaryStat: 'ratio@illuminator/connector',
  },
  {
    title: 'Buff Those Portals',
    description: 'Engineer',
    customUrl: 'https://eigood.github.io/wicked-houston-data/iwwc-custom-20250907.json',
    infoUrl: 'https://eigood.github.io/wicked-houston-data/iwwc-info-20250907.json',
    startDate: '2025-09-07',
    endDate: '2025-09-20',
    primaryStat: 'engineer',
  },
  {
    title: 'Efficient Farmer',
    description: 'Translator / Hacker',
    customUrl: 'https://eigood.github.io/wicked-houston-data/iwwc-custom-20250928.json',
    infoUrl: 'https://eigood.github.io/wicked-houston-data/iwwc-info-20250928.json',
    startDate: '2025-09-28',
    endDate: '2025-10-11',
    primaryStat: 'ratio@translator/hacker',
  },
]

export const displayStats = [
  ['lifetime_ap', 'AP'],
  ['builder', 'Builder'],
  ['connector', 'Connector'],
  ['engineer', 'Engineer'],
  ['explorer', 'Explorer'],
  ['hacker', 'Hacker'],
  ['illuminator', 'Illuminator'],
  ['crafter', 'Kinetic Capsules Completed'],
  ['liberator', 'Liberator'],
  ['maverick', 'Maverick'],
  ['mind-controller', 'Mind Controller'],
  ['overclocker', 'Overclock'],
  ['pioneer', 'Pioneer'],
  ['purifier', 'Purifier'],
  ['recharger', 'Recharger'],
  ['reclaimer', 'Reclaimer'],
  ['recon', 'Recon'],
  ['recursions', 'Recursions'],
  ['scout', 'Scout'],
  ['scout_controller', 'Scout Controller'],
  ['specops', 'Specops'],
  ['translator', 'Translator'],
  ['trekker', 'Trekker'],
  ['SEPARATOR', 'Extra Values'],
  ['ratio@mu/field', 'MindUnits / Field'],
  ['ratio@fields/link', 'Fields / Link'],
  ['ratio@pioneer/explorer', 'Pioneeer / Explorer'],
  ['ratio@ap/hack', 'AP / Hack'],
  ['ratio@translator/hacker', 'Translator / Hacker'],
  ['ratio@purifier/builder', 'Purifier / Builder'],
  ['ratio@ap/trekker', 'AP / km'],
  ['ratio@builder/purifier', 'Builder / Purifier'],
  ['ratio@connector/illuminator', 'Connector / Illuminator'],
  ['ratio@illuminator/connector', 'Illuminator / Connector'],
  ['last_submit', 'Last Submit'],
]
